export type TqtSettings = typeof defaultSettings;

export const copySchema = {
  cta_check_area: 'CHECK MY AREA',
  cta_show_price: 'SHOW PRICE',
  cta_signup: 'SIGN UP',
  coupon_trigger_label: 'Have a coupon?',
  coupon_modal_title: 'Add a coupon',
  coupon_input_placeholder: 'Coupon code',
  zip_input_placeholder: 'ZIP code',
  coupon_apply_button: 'Apply',
  coupon_help_toggle: 'No code? Tap to get current specials.',
  coupon_help_copy: 'Enter your phone number and we will text the latest offers.',
  coupon_help_phone_placeholder: 'Phone number',
  coupon_help_button: 'Text me',
  waitlist_copy: 'Oh no - we are not in your area yet. Drop your email and we will reach out as soon as service opens up.',
  waitlist_input_placeholder: 'Email address',
  waitlist_button: 'NOTIFY ME',
  onboard_first_name_placeholder: 'First name',
  onboard_last_name_placeholder: 'Last name',
  onboard_email_placeholder: 'Email',
  onboard_phone_placeholder: 'Phone',
  onboard_street_placeholder: 'Home address',
  onboard_city_placeholder: 'City',
  onboard_state_placeholder: 'State',
  onboard_addons_label: 'Add-ons (optional)',
  onboard_secondary_button: 'More info',
  onboard_cancel_button: 'Cancel',
  onboard_submit_button: 'REGISTER',
  success_title: 'You are all set',
  success_body: 'We will reach out within <strong>24 hours</strong> to schedule your first visit.',
  success_button: 'Done',
  credit_card_link_success: 'We will send a secure card-on-file link shortly.',
};

export const defaultSettings = {
  org_slug: '',
  base_url: 'https://openapi.sweepandgo.com',
  email_to: '',
  enable_partial_lead_email: false,
  contact_phone: '',
  google_tag_id: '',
  meta_pixel_id: '',
  privacy_url: 'https://example.com/privacy-policy',
  terms_url: 'https://example.com/terms',
  location_id: '',
  organization_form_id: '',
  manual_dogs: '',
  manual_frequencies: '',
  manual_pricing: '',
  yard_size_adjustments: '',
  one_time_price: '',
  one_time_price_per_extra_dog: '',
  one_time_extra_time_block_minutes: '30',
  one_time_extra_time_block_price: '',
  pricing_notice_recurring: '',
  pricing_notice_one_time: '',
  service_data_source: 'sng',
  local_area_mode: 'zip',
  local_area_values: '',
  lead_destination: 'sng',
  ghl_webhook_url: '',
  jobber_webhook_url: '',
  jobber_webhook_secret: '',
  send_credit_card_link_after_registration: false,
  credit_card_link_message: 'Thanks for signing up. Please use the secure Sweep&Go link to add your card on file.',
  dog_slider_icon_mode: 'emoji',
  dog_slider_icon_emoji: '💩',
  dog_slider_icon_image: '',
  freq_slider_icon_mode: 'emoji',
  freq_slider_icon_emoji: '⏱️',
  freq_slider_icon_image: '',
  slider_track_color: '#e2e8f0',
  slider_fill_color: '#1f86ea',
  slider_thumb_color: '#1f86ea',
  slider_thumb_size: '28',
  slider_track_height: '6',
  slider_icon_size: '28',
  panel_bg: '#e7e2d9',
  panel_transparent: false,
  panel_border: '#000000',
  text: '#263238',
  muted: '#6b7b83',
  trust_color: '#6b7b83',
  accent: '#ff8a00',
  cta: '#1f86ea',
  cta_text_color: '#ffffff',
  cta_font_size: '18',
  cta_font_weight: '900',
  price_font_size: '32',
  price_font_weight: '900',
  heading_font_url: '',
  heading_font_family: '"Luckiest Guy", system-ui, sans-serif',
  body_font_url: '',
  body_font_family: 'ui-sans-serif, system-ui, Segoe UI, Roboto, Helvetica, Arial, sans-serif',
  title_font_url: '',
  title_font_family: '',
  title_font_size: '22',
  title_align: 'left',
  zip_heading_font_url: '',
  zip_heading_font_family: '',
  zip_body_font_url: '',
  zip_body_font_family: '',
  zip_title_font_url: '',
  zip_title_font_family: '',
  zip_title_font_size: '',
  zip_title_align: '',
  zip_widget_title: '',
  zip_hint_text: '',
  zip_require_phone_before_quote: false,
  zip_require_name_before_quote: false,
  zip_require_consent_before_quote: false,
  zip_show_last_cleaned: false,
  zip_enable_coupon_field: false,
  zip_cta_text_color: '',
  zip_cta_font_size: '',
  zip_cta_font_weight: '',
  widget_title: 'Get an Instant Quote',
  hint_text: 'Enter ZIP, then pick dogs & frequency.',
  radius: '16',
  bullets: 'Local, insured techs\nNo contracts - cancel anytime',
  custom_css: '',
  require_phone_before_quote: false,
  require_name_before_quote: false,
  require_consent_before_quote: true,
  show_last_cleaned: true,
  enable_coupon_field: true,
  dog_control_type: 'dropdown',
  frequency_control_type: 'dropdown',
  addon2_label: '',
  addon2_price: '',
  addon2_desc: '',
  show_sng_addons_by_default: true,
  show_per_cleanup_price: true,
  recurring_calc_mode: 'standard',
  loader_message: 'Creating your personalized quote...',
  loader_min_time: '1500',
  copy_overrides: {} as Record<string, string>,
  mapbox_token: '',
  enable_yard_map: false,
};

export function mergeSettings(raw: any) {
  return { ...defaultSettings, ...(raw && typeof raw === 'object' ? raw : {}) };
}

export function copyStrings(settings: any) {
  const overrides = settings?.copy_overrides && typeof settings.copy_overrides === 'object' ? settings.copy_overrides : {};
  return Object.fromEntries(Object.entries(copySchema).map(([key, value]) => [key, overrides[key] || value]));
}
